language: node_js
node_js:
  - node
  - '6'
addons:
  sauce_connect: true
install:
  - npm install
  - npm install -g nightwatch
before_script:
  - npm start &
  - sleep 3
script:
  - npm test
  - nightwatch --config nightwatch.conf.js --env chrome
  - pkill node
env:
  global:
    - secure: pN09Kr9N3tGLg16obmCWcEZ19W7uJo5Y75jF8QL/BN27Q9qqoFzhh+emkVR2isSdZpEbFiHPwaBD4puxdVqyjXqVOlbzNUizj9aZvy78y10ZMnsQwTeSMkX8GdJrUA6vRgncW/B8Iej6QK4CzQpAMqrsDOD1DyWJfQo7WZdr4WOwnyAOh5a3vuv5GMeQW17ImItJJjEyGdWQSpX7AzS++4zx0ZUhiv1wUudcGcuYe8SVm4MVpzb6xCXAtxodAC9Hpr+75tTJ9QS4sw779RYT0+XI7RH/lxuoKUJWRdyJEXr8LcnbWebCyZfygCxiddpkV6RWRD085wSKny4xhyy4XZK0dkTyNwgMsIcgqy2BFvTvVNLH7J1aljTt2EbOMyQ4MG0C/mhgTki0vEHOAthgpiYgag9Hy7dL90Y6p6hISjK/WKtahMfjTaIIHvPxgLEOKCFFRdx9hx8TzO0qeoPbisRQBS41ZTq6VJ2XzRjB0cQmnOceTG9Mf/pbxW64tuIGb1je3Ja7gl5mt5AR9bJoyV0v0/XCo9w7HFe3fwaB/6oAbj0l4cIr8MGQdRwbtaYCDJJ1l5TF+sfpnbAVtGnEG2L/y+mJpuUSIcfefO7trmRTskRI93Z6oMgmm9cQQHzrZ8f708DxVTdmTmGnldpfxjGhnZmhKJtS+QNxU2GRso8=
    - secure: aNpLw0v/PrHofH/kWcP81FWeEEAdQlyDqBv3MAbWDjJwzdR9ne5ow09p58lzOo4tGaavoDqPvnikDKKI1N3dlImaYZi0a2+5DfxpJ42p1GG1msnhh6crLJ+PPTrgvBJcKkBAgdA17zZUau3vQ5hMqyK+ySx9k1M8gunKj1S1lJWPIH4YtHcQkH7HaGNMnxAQOXu+pJJIDCg9dHxV7eYoMvQblkesPHD0PQAiKy7h5u7yOD9D0uAmbPPNPcJtpX/jrzH/lZrOI7hSEcqFotQ6KCZ/nx9uOHTc7KXLr+3rKJ1s51g5kP1Q2NIq7qwpPCYCVxlqT+igA3jSrRCsn7ru+Pf/AaitQihXNnC1ZAJ9v3LvgNg1e9Zf0NFJOrTU/ydtOU/aPPrnIl2uvmAQ/dJIJ14SBBrqn4bNmb46+fK19D+vafdKrahRF8W7vksdAp/Iv93aF/QSF+yhbFd3S6XnCpn1WQQkwWt9xfd1rXzXh1AHeCmUOSgzLrFinv3rputHSa2illEJmy29xzXgCnGcEnnPn+EY0GG+ddD3QFOOV8MJeOpri6OXBvHaqobGjAtcUcDPWn5HckV3VYB5qTlvnYl8nPeW6I1AHn/KNSoJNGYGCy7S08UHo0kkzVkcMYYjzdlNsv53Bi04RLzB0xc7sysjPIbp6McxYLjds+od1F0=
