---
- name: Install Nginx
  become: yes
  apt:
    name: nginx
    state: present

- name: Configure Nginx host
  become: yes
  copy:
    src: templates/etc/nginx/nginx.conf
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
  notify: restart nginx

- name: Run Nginx
  become: yes
  service: name=nginx state=started