---
- name: NodeSource install script
  become: yes
  command: bash -c "curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -"

- name: Install Node.JS
  become: yes
  apt:
    name: nodejs
    state: present