---
- name: Change owner (AWS)
  become: yes
  file:
    path: /var/www
    owner: ubuntu
    group: ubuntu
    state: directory
    recurse: yes

- name: Deploy files (AWS)
  copy:
    src: "../{{ item }}"
    dest: /var/www/
    owner: ubuntu
    group: ubuntu
  with_items: [ 'bin', 'public', 'routes', 'services', 'views', 'app.js', 'ecosystem.json', 'package.json' ]