---
- hosts: all
  become: yes

  tasks:
    - name: Nginx site config
      copy:
        src: templates/etc/nginx/sites-available/default
        dest: /etc/nginx/sites-available/default
        owner: root
        group: root
      notify: restart nginx

  handlers:
    - name: restart nginx
      service:
        name: nginx
        state: restarted